version: '3.1'

services:
  wp:
    build:
      context: '.'
      dockerfile: wp.Dockerfile
    volumes:
      - ./site:/app
    links:
      - db
    depends_on:
      - db
    ports:
      - 80:80
  node:
    build:
      context: '.'
      dockerfile: node.Dockerfile
    volumes:
      - ./site/web/app/themes/megane-v1.2:/app
  db:
    restart: always
    image: mariadb:10.3.0
    volumes:
      - dbOffshorly:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wp
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: wp  
      MYSQL_PASSWORD: wp

volumes:
  dbOffshorly:
