version: '3.1'

services:
  wp:
    build:
      context: '.'
      dockerfile: wp.Dockerfile
    container_name: megane-wordpress
    volumes:
      - ./site:/app
      - ./sites-enabled:/etc/nginx/sites-enabled
    networks:
      wp-network:
    depends_on:
      - db
  node:
    build:
      context: '.'
      dockerfile: node.Dockerfile
    volumes:
      - ./site/web/app/themes/megane-v1.2:/app
  db:
    restart: always
    image: mariadb:10.3.0
    container_name: megane-db
    volumes:
      - dbOffshorly:/var/lib/mysql
    networks:
      wp-network:
    environment:
      MYSQL_DATABASE: wp
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: wp  
      MYSQL_PASSWORD: wp

volumes:
  dbOffshorly:
networks:
  wp-network:
