version: '3.1'

services:
  wp:
    networks:
      external-network: 
        aliases:
          - megane-wordpress
    expose:
        - 80
  db:
    volumes:
      - volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 
      MYSQL_ROOT_PASSWORD:
      MYSQL_USER: 
      MYSQL_PASSWORD:

networks:
  external-network:
    external:
      name: nginx