version: '3.1'

services:
  wp:
    build:
      context: './dockerfiles'
      dockerfile: wp.Dockerfile
    container_name: megane-wordpress
    volumes:
      - ./site:/app
      - ./sites-enabled:/etc/nginx/sites-enabled
    networks:
      wp-network:
    depends_on:
      - db
      - memcached
  node:
    build:
      context: './dockerfiles'
      dockerfile: node.Dockerfile
    volumes:
      - ./site/web/app/themes/megane-v1.2:/app
  memcached:
    restart: always
    image: memcached:1.5.2-alpine
    container_name: megane-memcache
    networks:
      wp-network:
        aliases:
          - megane-memcache
  db:
    restart: always
    image: mariadb:10.3.0
    container_name: megane-db
    volumes:
      - dbMegane:/var/lib/mysql
    networks:
      wp-network:
    environment:
      MYSQL_DATABASE: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 
      MYSQL_ROOT_PASSWORD: EQZwJQia8w7m2gD1sPIKt38NiGcLbS
      MYSQL_USER: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  
      MYSQL_PASSWORD: e54ee7e285fbb0275279143abc4c554e5314e7b417ecac83a5984a964facbaad68866a2841c3e83ddf125a2985566261c4014f9f960ec60253aebcda9513a9b4

volumes:
  dbMegane:
networks:
  wp-network:
