<?php
/** Enable W3 Total Cache */
// define('WP_CACHE', true); // Added by W3 Total Cache

// If WordPress is behind reverse proxy
// which proxies https to http
if (
    (!empty( $_SERVER['HTTP_X_FORWARDED_HOST'])) ||
    (!empty( $_SERVER['HTTP_X_FORWARDED_FOR'])) )
{

  // http://wordpress.org/support/topic/wordpress-behind-reverse-proxy-1
  $_SERVER['HTTP_HOST'] = $_SERVER['HTTP_X_FORWARDED_HOST'];

  /*
  define('WP_HOME', 'https://bob.org:8080/blog');
  define('WP_SITEURL', 'https://bob.org:8080/blog');

  // rewrite blog word with wordpress
  $_SERVER['REQUEST_URI'] = str_replace("wordpress", "blog",
  $_SERVER['REQUEST_URI']);
  */

  // http://wordpress.org/support/topic/compatibility-with-wordpress-behind-a-reverse-proxy
  $_SERVER['HTTPS'] = 'on';
}

/**
 * Do not edit this file. Edit the config files found in the config/ dir instead.
 * This file is required in the root directory so WordPress can find it.
 * WP is hardcoded to look in its own directory or one directory up for wp-config.php.
 */
require_once(dirname(__DIR__) . '/vendor/autoload.php');
require_once(dirname(__DIR__) . '/config/application.php');
require_once(ABSPATH . 'wp-settings.php');
